org: pattabhi
app: lambda-serverless
service: lambda-layers

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
    layer: true
    layerName: my-layer
    layerVersion: 1
    description: My layer description